export const usersData = [
  {
    services: "Lhardy",
    Ss: "Local",
    name: "Hotelston",
    email: "Javier",
    address: "González",
    city: "ES ",
    country: "Hotels",
    status: "0",
    Email1: "Culture",
    active: true,
  },

  {
    services: "Palacio Real",
    Ss: "Private Tour",
    name: "Redsys",
    email: "Javier",
    address: "González",
    city: "ES",
    country: "Restaurants",
    status: "5",
    Email1: "Local",
    active: true,
  },

  {
    services: "Teatro Real",
    Ss: "Turandot Opera",
    name: "Viator",
    email: "Javier",
    address: "González",
    city: "ES",
    country: "Experiences",
    status: "7",
    Email1: "Culture",
    active: true,
  },
  {
    services: "Saddle",
    Ss: "Michelin star",
    name: "Hotelston",
    email: "Javier",
    address: "González",
    city: "ES ",
    country: "Hotels",
    status: "2350",
    Email1: "Culture",
    active: true,
  },
  {
    services: "Santo Mauro",
    Ss: "City Center",
    name: "Redsys",
    email: "Javier",
    address: "789 Rue Principale",
    city: "ES",
    country: "Experiences",
    status: "2350",
    Email1: "Entertainment",
    active: true,
  },
  {
    services: "Orfila",
    Ss: "City Center",
    name: "Hotelston",
    email: "Javier",
    address: "23 Calle Mayor",
    city: "ES ",
    country: "Hotels",
    status: "2350",
    Email1: "Alejandro Blanco",
    active: true,
  },
  {
    services: "ES Edition",
    Ss: "City Center",
    name: "CoverManager",
    email: "Javier",
    address: "789 Calle Granada",
    city: "ES",
    country: "Restaurant",
    status: "2350",
    Email1: "Sonia Reyes",
    active: true,
  },
  {
    services: "Casa Lucio",
    Ss: "Local",
    name: "Redsys",
    email: "Javier",
    address: "789 Rue Principale",
    city: "ES",
    country: "Restaurant",
    status: "2350",
    Email1: "Sonia Reyes",
    active: true,
  },
];

export const SuppliesData = [
  {
    name: "Hotelston",
    email: "Hotel",
    address: "23 Calle Mayor",
    city: "Diego Canto ",
    country: "-",
    status: "93 012 3456",
    Email1: "diego.canto@email.com",
    active: true,
  },
  {
    name: "Viator",
    email: "Experience",
    address: "456 Avenida Principal",
    city: "Marta Ruiz",
    country: "Carmen Nuñez",
    status: "93 012 3456",
    Email1: "marta.ruiz@email.com",
    active: true,
  },
  {
    name: "CoverManager",
    email: "Restaurant",
    address: "789 Calle Granada",
    city: "Ana Martínez",
    country: "-",
    status: "93 012 3456",
    Email1: "marta.ruiz@email.com",
    active: true,
  },
  {
    name: "Redsys",
    email: "Payments",
    address: "789 Rue Principale",
    city: "Lea Dubois",
    country: "Eloise Lamarc",
    status: "93 012 3456",
    Email1: "marta.ruiz@email.com",
    active: true,
  },
];

export const ServicesData = [
  {
    services: "Lhardy",
    Ss: "Local",
    name: "Hotelston",
    email: "Hotel",
    address: "23 Calle Mayor",
    city: "Madrid ",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Marta Ruiz",
    active: true,
  },

  {
    services: "Palacio Real",
    Ss: "Private Tour",
    name: "Redsys",
    email: "Payments",
    address: "789 Rue Principale",
    city: "Madrid",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Ana Martínez",
    active: true,
  },

  {
    services: "Teatro Real",
    Ss: "Turandot Opera",
    name: "Viator",
    email: "Experience",
    address: "456 Avenida Principal",
    city: "Madrid",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Lea Dubois",
    active: true,
  },
  {
    services: "Saddle",
    Ss: "Michelin star",
    name: "Hotelston",
    email: "Hotel",
    address: "23 Calle Mayor",
    city: "Madrid ",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Martin López",
    active: true,
  },
  {
    services: "Santo Mauro",
    Ss: "City Center",
    name: "Redsys",
    email: "Payments",
    address: "789 Rue Principale",
    city: "Madrid",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Sonia Reyes",
    active: true,
  },
  {
    services: "Orfila",
    Ss: "City Center",
    name: "Hotelston",
    email: "Hotel",
    address: "23 Calle Mayor",
    city: "Madrid ",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Alejandro Blanco",
    active: true,
  },
  {
    services: "Madrid Edition",
    Ss: "City Center",
    name: "CoverManager",
    email: "Restaurant",
    address: "789 Calle Granada",
    city: "Madrid",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Sonia Reyes",
    active: true,
  },
  {
    services: "Casa Lucio",
    Ss: "Local",
    name: "Redsys",
    email: "Payments",
    address: "789 Rue Principale",
    city: "Madrid",
    country: "Spain",
    status: "93 012 3456",
    Email1: "Sonia Reyes",
    active: true,
  },
];

export const ItinerariesData = [
  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Javier",
    city: "Madrid ",
    country: "Spain",
    status: "González",
    Email1: "Marta Ruiz",
    active: true,
    avatar: "10/06/2024",
  },

  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Javier",
    city: "Madrid",
    country: "Spain",
    status: "González",
    Email1: "Ana Martínez",
    active: true,
    avatar: "10/06/2024",
  },

  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Javier",
    city: "Madrid",
    country: "Spain",
    status: "González",
    Email1: "Lea Dubois",
    active: true,
    avatar: "10/06/2024",
  },
  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Javier",
    city: "Madrid ",
    country: "Spain",
    status: "González",
    Email1: "Martin López",
    active: true,
    avatar: "10/06/2024",
  },
  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Drew",
    city: "Madrid",
    country: "Spain",
    status: "González",
    Email1: "Sonia Reyes",
    active: true,
    avatar: "10/06/2024",
  },
  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Drew",
    city: "Madrid ",
    country: "Spain",
    status: "González",
    Email1: "Alejandro Blanco",
    active: true,
    avatar: "10/06/2024",
  },
  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Drew",
    city: "Madrid",
    country: "Spain",
    status: "González",
    Email1: "Sonia Reyes",
    active: true,
    avatar: "10/06/2024",
  },
  {
    services: "12032024001",
    Ss: "Madrid",
    name: "Marta Ruiz",
    email: "marta.ruiz@email.com",
    address: "Adcs",
    city: "Madrid",
    country: "Spain",
    status: "González",
    Email1: "Sonia Reyes",
    active: true,
    avatar: "10/06/2024",
  },
];
